Repository tu2-atmanand/Task-Board, pull requests merged in 2025-07, with the labels that each got.

#270 Added frontmatter inheritance
  src/components/Column.tsx
  src/components/TaskItem.tsx
  src/interfaces/GlobalSettings.ts
  src/interfaces/TaskItem.ts
  src/modal/AddOrEditTaskModal.tsx
  src/settings/TaskBoardSettingConstructUI.ts
  src/utils/RealTimeScanning.ts
  src/utils/RenderColumns.ts
  src/utils/ScanningVault.ts
  src/utils/TaskItemUtils.ts
  src/utils/lang/locale/en.ts
Labels: feature, enhancement

#272 Added reorder boards
  src/modal/BoardConfigModal.tsx
Labels: feature

#306 FR : A canvas view for organizing the tasks visually
  data.json
  main.css
  package-lock.json
  package.json
  src/components/CanvasView.tsx
  src/components/TaskBoardViewContent.tsx
  src/components/TaskItem.tsx
  styles.css
  tasks.json
Labels: feature

#303 Update the russian translation
  src/utils/lang/locale/ru.ts
Labels: enhancement
